#!/bin/bash

source_folder="source"
data_folder="data"
search_folder="../packages"
mongourl="mongodb://192.168.1.111:11223"

WORKING_DIR=`pwd`
# TODO: use this properly
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

function compile_and_gen () {
    if [[ "$1" == *.tex ]]; then
        # generate from LaTeX
        echo "Compiling $1"
        tectonic "$1" -Z search-path="$search_folder" > /dev/null

        echo "Generating snippets from $1"
        pdf=$(echo "$1" | sed 's/\.tex$/.pdf/');
        RUST_LOG=debug stellar-cli generate snippets \
            --input "$pdf" \
            --data-output "$data_folder" \
            --bottom-offset 9.5 \
            --top-offset=-20 \
            --import \
            --connection-url "$mongourl";

        # You should compile all the snippets before generating PDFs
        #echo "Generating PDF from $1"
        #stellar-cli generate pdf \
        #    --input "$pdf" \
        #    --data "$data_folder" \
        #    --output "$pdf";

        rm "$pdf";
    elif [ -e "$1/Cargo.toml" ]; then
        # compile nannou

        snippet_name=$(basename "$1")
        
        # cleanup old versions
        if [ -e "$1/website/dist/index.js" ]; then
            rm "$1/website/dist/index.js"
        fi
        if [ -e "$data_folder/snippets/$snippet_name" ]; then
            rm -rf "$data_folder/snippets/$snippet_name*"
        fi

        cd "$1"
        # compile using shared folder to cache shared packages
        CARGO_TARGET_DIR="../target" wasm-pack build

        cd website
        npm install --dry-run --quiet || npm install # run install only if necessary
        npm run build

        cd "$WORKING_DIR"
        mkdir -p "$data_folder/snippets/$snippet_name"

        # generate snippet folder
        rm "$1/website/dist/index.js"
        mv "$1"/website/dist/* "$data_folder/snippets/$snippet_name"
    fi
}

if [ $# -gt 0 ]; then
    compile_and_gen "$1"
else
    for file in "$source_folder"/*; do
        compile_and_gen "$file"
    done
fi

cd "$WORKING_DIR"
