#!/bin/bash

WORKING_DIR=`pwd`
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

cd "$SCRIPT_DIR"

# get last pull files files
output="$(git diff --name-status HEAD@{1}..HEAD)"

# TODO:
# git will give various files like
# - source/folder/file1.html
# - source/folder/file1.html
# and the scripts need to compile "source/folder" only once

IFS=$'\n'  # Set the Internal Field Separator to newline
for line in $output; do
    if [[ $line == *"source/"* ]]; then
        file=$(echo "$line" | sed 's/.*\/source/source/') # remove everything before "source"
        echo $file
        #./compile $file
    fi
done

cd "$WORKING_DIR"