#!/bin/bash

source_folder="source"
data_folder="data"
search_folder="../packages"
mongourl="mongodb://localhost:11223"

WORKING_DIR=`pwd`
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

cd $SCRIPT_DIR

function compile_and_gen () {
    if [[ "$1" == *.tex ]]; then
        echo "Compiling $1"
        tectonic "$1" -Z search-path="$search_folder" > /dev/null

        echo "Generating snippets from $1"
        pdf=$(echo "$1" | sed 's/\.tex$/.pdf/');
        RUST_LOG=debug stellar-cli generate snippets \
            --input "$pdf" \
            --data-output "$data_folder" \
            --bottom-offset 9.5 \
            --top-offset=-20
            #--import \
            #--connection-url "$mongourl";

        # You should compile all the snippets before generating PDFs
        #echo "Generating PDF from $1"
        #stellar-cli generate pdf \
        #    --input "$pdf" \
        #    --data "$data_folder" \
        #    --output "$pdf";

        rm "$pdf";
    fi
}

if [ $# -gt 0 ]; then
    compile_and_gen "$1"
else
    for file in "$source_folder"/*; do
        compile_and_gen "$file"
    done
fi

cd $WORKING_DIR
