// Stellar definition commands for Typst
// Faithful port of definitions.sty (2023/01/01)
// Target: Typst 0.15.x
//
// Text commands follow this calling convention:
//   #category()                         -> default text
//   #category(text: [categories])       -> replacement text
//   #category(text: [open], link-label: "Open")
//
// The LaTeX command \set conflicts with Typst's #set keyword and is therefore
// exported as #set-term(). All other source names are kept where practical.
// Nullary math commands such as catob, cathom, sin, det, and expectation
// are content values, not functions. Write `$catob (cal(C))$`, preserving a
// space before the ordinary parenthesized expression.

#import "stellar.typ" as _stellar

#let _text-ref(identifier, label, default, text: none, link-label: none) = {
  let shown = if text == none { default } else { text }
  let effective-label = if link-label == none { label } else { link-label }
  _stellar.snippetref(identifier + "|" + effective-label, body: shown)
}

#let _black(body) = text(fill: black, body)

#let _math-ref(identifier, label, body, class: none, operator: false) = {
  let linked = _stellar.snippetref(identifier + "|" + label, body: _black(body))
  if operator {
    math.op(linked)
  } else if class != none {
    math.class(class, linked)
  } else {
    linked
  }
}

#let _label-math(label, body, class: none, operator: false) = {
  let linked = _stellar.labelref(label, _black(body))
  if operator {
    math.op(linked)
  } else if class != none {
    math.class(class, linked)
  } else {
    linked
  }
}

#let _append(head, tail) = if tail == none { head } else { [#head#tail] }

#let _subscripted(head, subscript: none, tail: none) = {
  let decorated = if subscript == none {
    head
  } else {
    math.attach(head, b: subscript)
  }
  if tail == none { decorated } else { [#decorated#tail] }
}

// Generic escape hatches, useful for commands not yet given a named wrapper.
#let textref(identifier, label, default, text: none, link-label: none) = {
  _text-ref(identifier, label, default, text: text, link-label: link-label)
}
#let mathref(identifier, label, body, class: none, operator: false) = {
  _math-ref(identifier, label, body, class: class, operator: operator)
}

// ---------- Textual reference commands ----------
#let set-term(text: none, link-label: none) = _text-ref("set-definition", "Set", "set", text: text, link-label: link-label)
#let axiomofinduction(text: none, link-label: none) = _text-ref("axiom-of-induction", "Axiom of induction", "axiom of induction", text: text, link-label: link-label)
#let principleofinduction(text: none, link-label: none) = _text-ref("weak-induction-theorem", "Principle of induction", "principle of induction", text: text, link-label: link-label)
#let stronginduction(text: none, link-label: none) = _text-ref("strong-induction-theorem", "Strong induction", "strong induction", text: text, link-label: link-label)
#let countable(text: none, link-label: none) = _text-ref("countable-set-definition", "Countable set", "countable", text: text, link-label: link-label)
#let disjoint(text: none, link-label: none) = _text-ref("disjoint-sets-definition", "Disjoint", "disjoint", text: text, link-label: link-label)
#let binrelation(text: none, link-label: none) = _text-ref("binary-relation-definition", "Binary relation", "binary relation", text: text, link-label: link-label)
#let binoperation(text: none, link-label: none) = _text-ref("binary-operation-definition", "Binary operation", "binary operation", text: text, link-label: link-label)
#let homrelation(text: none, link-label: none) = _text-ref("homogeneous-relation-definition", "Homogeneous relation", "homogeneous relation", text: text, link-label: link-label)
#let equivrelation(text: none, link-label: none) = _text-ref("equivalence-relation-definition", "Equivalence relation", "equivalence relation", text: text, link-label: link-label)
#let equivclass(text: none, link-label: none) = _text-ref("equivalence-class-definition", "Equivalence class", "equivalence class", text: text, link-label: link-label)
#let congruenceclass(text: none, link-label: none) = _text-ref("congruence-class-definition", "Congruence class", "congruence class", text: text, link-label: link-label)
#let invertiblecongclass(text: none, link-label: none) = _text-ref("invertible-congruent-class-definition", "Invertible congruence class", "invertible congruence class", text: text, link-label: link-label)
#let quotset(text: none, link-label: none) = _text-ref("quotient-set-definition", "Quotient set", "quotient set", text: text, link-label: link-label)
#let partition(text: none, link-label: none) = _text-ref("set-partition-definition", "Partition", "partition", text: text, link-label: link-label)
#let preorder(text: none, link-label: none) = _text-ref("preorder-definition", "Preorder", "preorder", text: text, link-label: link-label)
#let partialorder(text: none, link-label: none) = _text-ref("partial-order-definition", "Partial order", "partial order", text: text, link-label: link-label)
#let poset(text: none, link-label: none) = _text-ref("poset-definition", "Partial ordered set", "poset", text: text, link-label: link-label)
#let totalorder(text: none, link-label: none) = _text-ref("total-order-definition", "Total order", "total order", text: text, link-label: link-label)
#let upperbound(text: none, link-label: none) = _text-ref("upper-bound-definition", "Upper bound", "upper bound", text: text, link-label: link-label)
#let lowerbound(text: none, link-label: none) = _text-ref("lower-bound-definition", "Lower bound", "lower bound", text: text, link-label: link-label)
#let bounded(text: none, link-label: none) = _text-ref("bounded-set-definition", "Bounded set", "bounded", text: text, link-label: link-label)
#let greatestelement(text: none, link-label: none) = _text-ref("greatest-element-definition", "Greatest element", "greatest element", text: text, link-label: link-label)
#let leastelement(text: none, link-label: none) = _text-ref("least-element-definition", "Least element", "least element", text: text, link-label: link-label)
#let maximalelement(text: none, link-label: none) = _text-ref("maximal-element-definition", "Maximal element", "maximal element", text: text, link-label: link-label)
#let minimalelement(text: none, link-label: none) = _text-ref("minimal-element-definition", "Minimal element", "minimal element", text: text, link-label: link-label)
#let function(text: none, link-label: none) = _text-ref("function-definition", "Function", "function", text: text, link-label: link-label)
#let stepfunction(text: none, link-label: none) = _text-ref("step-function-definition", "Step function", "step function", text: text, link-label: link-label)
#let curve(text: none, link-label: none) = _text-ref("curve-definition", "Curve", "curve", text: text, link-label: link-label)
#let regularcurve(text: none, link-label: none) = _text-ref("regular-curve-definition", "Regular curve", "regular", text: text, link-label: link-label)
#let lineartransformation(text: none, link-label: none) = _text-ref("linear-transformation-definition", "Linear transformation", "linear transformation", text: text, link-label: link-label)
#let linearendomorphism(text: none, link-label: none) = _text-ref("linear-endomorphism-definition", "Linear endomorphism", "endomorphism", text: text, link-label: link-label)
#let linearisomorphism(text: none, link-label: none) = _text-ref("linear-isomorphism-definition", "Linear isomorphism", "isomorphism", text: text, link-label: link-label)
#let linearfunctional(text: none, link-label: none) = _text-ref("linear-functional-definition", "Linear functional", "linear functional", text: text, link-label: link-label)
#let covector(text: none, link-label: none) = _text-ref("dual-space-definition", "Covector", "covector", text: text, link-label: link-label)
#let dualbasis(text: none, link-label: none) = _text-ref("dual-basis-definition", "Dual basis", "dual basis", text: text, link-label: link-label)
#let associatedmatrix(text: none, link-label: none) = _text-ref("linear-map-associated-matrix-definition", "Associated matrix", "associated matrix", text: text, link-label: link-label)
#let changeofbasismatrix(text: none, link-label: none) = _text-ref("change-of-basis-matrix-definition", "Change-of-basis matrix", "change-of-basis matrix", text: text, link-label: link-label)
#let similarmatrices(text: none, link-label: none) = _text-ref("similar-matrices-definition", "Similar matrices", "similar", text: text, link-label: link-label)
#let linearautomorphism(text: none, link-label: none) = _text-ref("linear-automorphism-definition", "Linear automorphism", "automorphism", text: text, link-label: link-label)
#let endomorphismdeterminant(text: none, link-label: none) = _text-ref("endomorphism-determinant-definition", "Determinant of an endomorphism", "determinant", text: text, link-label: link-label)
#let orientation(text: none, link-label: none) = _text-ref("vector-space-orientation-definition", "Orientation", "orientation", text: text, link-label: link-label)
#let sameorientation(text: none, link-label: none) = _text-ref("same-orientation-bases-definition", "Same orientation", "same orientation", text: text, link-label: link-label)
#let orientationpreserving(text: none, link-label: none) = _text-ref("orientation-preserving-automorphism-definition", "Orientation-preserving", "orientation-preserving", text: text, link-label: link-label)
#let orientationreversing(text: none, link-label: none) = _text-ref("orientation-reversing-automorphism-definition", "Orientation-reversing", "orientation-reversing", text: text, link-label: link-label)
#let linearprojection(text: none, link-label: none) = _text-ref("linear-projection-definition", "Linear projection", "projection", text: text, link-label: link-label)
#let simplefunction(text: none, link-label: none) = _text-ref("simple-function-definition", "Simple function", "simple function", text: text, link-label: link-label)
#let injective(text: none, link-label: none) = _text-ref("injectivity-definition", "Injective", "injective", text: text, link-label: link-label)
#let surjective(text: none, link-label: none) = _text-ref("surjectivity-definition", "Surjective", "surjective", text: text, link-label: link-label)
#let bijective(text: none, link-label: none) = _text-ref("bijectivity-definition", "Bijective", "bijective", text: text, link-label: link-label)
#let monoid(text: none, link-label: none) = _text-ref("monoid-definition", "Monoid", "monoid", text: text, link-label: link-label)
#let algebraicstructure(text: none, link-label: none) = _text-ref("algebraic-structure-definition", "Algebraic structure", "algebraic structure", text: text, link-label: link-label)
#let group(text: none, link-label: none) = _text-ref("group-definition", "Group", "group", text: text, link-label: link-label)
#let groupoid(text: none, link-label: none) = _text-ref("groupoid-definition", "Groupoid", "groupoid", text: text, link-label: link-label)
#let subgroup(text: none, link-label: none) = _text-ref("subgroup-definition", "Subgroup", "subgroup", text: text, link-label: link-label)
#let subring(text: none, link-label: none) = _text-ref("subring-definition", "Subring", "subring", text: text, link-label: link-label)
#let ideal(text: none, link-label: none) = _text-ref("ring-ideal-definition", "Ideal", "ideal", text: text, link-label: link-label)
#let principalideal(text: none, link-label: none) = _text-ref("principal-ideal-definition", "Principal ideal", "principal ideal", text: text, link-label: link-label)
#let principalidealdomain(text: none, link-label: none) = _text-ref("principal-ideal-definition", "Principal ideal domain", "principal ideal domain", text: text, link-label: link-label)
#let primeideal(text: none, link-label: none) = _text-ref("prime-ideal-definition", "Prime ideal", "prime ideal", text: text, link-label: link-label)
#let maximalideal(text: none, link-label: none) = _text-ref("maximal-ideal-definition", "maximal ideal", "maximal ideal", text: text, link-label: link-label)
#let sylowpsubgroup(text: none, link-label: none) = _text-ref("sylow-subgroup-definition", "Sylow subgroup", "Sylow p-subgroup", text: text, link-label: link-label)
#let submonoid(text: none, link-label: none) = _text-ref("submonoid-definition", "Submonoid", "submonoid", text: text, link-label: link-label)
#let cyclicgroup(text: none, link-label: none) = _text-ref("cyclic-group-definition", "Cyclic group", "cyclic group", text: text, link-label: link-label)
#let abeliangroup(text: none, link-label: none) = _text-ref("abelian-group-definition", "Abelian group", "abelian group", text: text, link-label: link-label)
#let isometry(text: none, link-label: none) = _text-ref("isometry-definition", "Isometry", "isometry", text: text, link-label: link-label)
#let symmetricgroup(text: none, link-label: none) = _text-ref("symmetric-group-definition", "Symmetric group", "symmetric group", text: text, link-label: link-label)
#let permutationgroup(text: none, link-label: none) = _text-ref("permutation-group-definition", "Permutation group", "permutation group", text: text, link-label: link-label)
#let disjointperm(text: none, link-label: none) = _text-ref("disjoint-permutations-definition", "Disjoint permutations", "disjoint", text: text, link-label: link-label)
#let permswap(text: none, link-label: none) = _text-ref("swap-permutation-definition", "Permutation swap", "swap", text: text, link-label: link-label)
#let permtype(text: none, link-label: none) = _text-ref("permutation-type-definition", "Permutation type", "type", text: text, link-label: link-label)
#let normalsubgrptext(text: none, link-label: none) = _text-ref("normal-subgroup-definition", "Normal subgroup", "normal", text: text, link-label: link-label)
#let ring(text: none, link-label: none) = _text-ref("ring-definition", "Ring", "ring", text: text, link-label: link-label)
#let algebra(text: none, link-label: none) = _text-ref("algebra-definition", "Algebra", "algebra", text: text, link-label: link-label)
#let commutativering(text: none, link-label: none) = _text-ref("commutative-ring-definition", "Commutative ring", "commutative ring", text: text, link-label: link-label)
#let field(text: none, link-label: none) = _text-ref("field-definition", "Field", "field", text: text, link-label: link-label)
#let setfinite(text: none, link-label: none) = _text-ref("finite-set-definition", "Finite set", "finite", text: text, link-label: link-label)
#let axiomofchoice(text: none, link-label: none) = _text-ref("axiom-of-choice", "Axiom of choice", "axiom of choice", text: text, link-label: link-label)
#let eventually(text: none, link-label: none) = _text-ref("eventually-definition", "Eventually", "eventually", text: text, link-label: link-label)
#let category(text: none, link-label: none) = _text-ref("category-definition", "Category", "category", text: text, link-label: link-label)
#let functor(text: none, link-label: none) = _text-ref("functor-definition", "Functor", "functor", text: text, link-label: link-label)
#let naturaltransformation(text: none, link-label: none) = _text-ref("natural-transformation-definition", "Natural transformation", "natural transformation", text: text, link-label: link-label)
#let monomorphism(text: none, link-label: none) = _text-ref("monomorphism-definition", "Monomorphism", "monomorphism", text: text, link-label: link-label)
#let epimorphism(text: none, link-label: none) = _text-ref("epimorphism-definition", "Epimorphism", "epimorphism", text: text, link-label: link-label)
#let catisomorphism(text: none, link-label: none) = _text-ref("cat-theory-isomorphism-definition", "Isomorphism", "isomorphism", text: text, link-label: link-label)
#let presheaf(text: none, link-label: none) = _text-ref("presheaf-definition", "Presheaf", "presheaf", text: text, link-label: link-label)
#let sheaf(text: none, link-label: none) = _text-ref("sheaf-definition", "Sheaf", "sheaf", text: text, link-label: link-label)
#let metricspace(text: none, link-label: none) = _text-ref("metric-space-definition", "Metric space", "metric space", text: text, link-label: link-label)
#let distancefunctiontext(text: none, link-label: none) = _text-ref("distance-function-definition", "Distance function", "distance function", text: text, link-label: link-label)
#let openball(text: none, link-label: none) = _text-ref("metricspaces-open-ball-definition", "Open ball", "open ball", text: text, link-label: link-label)
#let msopenset(text: none, link-label: none) = _text-ref("metricspaces-open-set-definition", "Open set", "open set", text: text, link-label: link-label)
#let msclosedset(text: none, link-label: none) = _text-ref("metricspaces-closed-set-definition", "Closed set", "closed set", text: text, link-label: link-label)
#let mscauchy(text: none, link-label: none) = _text-ref("metricspaces-cauchy-sequence-definition", "Cauchy sequence", "Cauchy", text: text, link-label: link-label)
#let msconvergence(text: none, link-label: none) = _text-ref("metric-space-convergence-definition", "Convergence", "convergence", text: text, link-label: link-label)
#let mscomplete(text: none, link-label: none) = _text-ref("metric-space-complete-definition", "Complete metric space", "complete", text: text, link-label: link-label)
#let contraction(text: none, link-label: none) = _text-ref("contraction-definition", "Contraction", "contraction", text: text, link-label: link-label)
#let monoidhomomorphism(text: none, link-label: none) = _text-ref("monoid-homomorphism-definition", "Monoid homomorphism", "monoid homomorphism", text: text, link-label: link-label)
#let grouphomomorphism(text: none, link-label: none) = _text-ref("group-homomorphism-definition", "Group homomorphism", "group homomorphism", text: text, link-label: link-label)
#let ringhomomorphism(text: none, link-label: none) = _text-ref("ring-homomorphism-definition", "Ring homomorphism", "ring homomorphism", text: text, link-label: link-label)
#let groupisomorphism(text: none, link-label: none) = _text-ref("group-isomorphism-definition", "Group isomorphism", "group isomorphism", text: text, link-label: link-label)
#let ringisomorphism(text: none, link-label: none) = _text-ref("ring-isomorphism-definition", "Ring isomorphism", "ring isomorphism", text: text, link-label: link-label)
#let fieldhomomorphism(text: none, link-label: none) = _text-ref("field-homomorphism-definition", "Field homomorphism", "field homomorphism", text: text, link-label: link-label)
#let fieldisomorphism(text: none, link-label: none) = _text-ref("field-isomorphism-definition", "Field isomorphism", "field isomorphism", text: text, link-label: link-label)
#let topologicalspace(text: none, link-label: none) = _text-ref("topological-space-definition", "Topological space", "topological space", text: text, link-label: link-label)
#let topologicalbasis(text: none, link-label: none) = _text-ref("topological-space-basis-definition", "Basis", "basis", text: text, link-label: link-label)
#let topologicalimmersion(text: none, link-label: none) = _text-ref("topological-space-immersion-definition", "Immersion", "immersion", text: text, link-label: link-label)
#let neighborhood(text: none, link-label: none) = _text-ref("neighbourhood-definition", "Neighborhood", "neighborhood", text: text, link-label: link-label)
#let closedset(text: none, link-label: none) = _text-ref("closed-set-definition", "Closed set", "closed set", text: text, link-label: link-label)
#let openset(text: none, link-label: none) = _text-ref("topological-space-definition", "Open set", "open set", text: text, link-label: link-label)
#let boundarypoint(text: none, link-label: none) = _text-ref("boundary-point-definition", "Boundary point", "boundary point", text: text, link-label: link-label)
#let interiorpoint(text: none, link-label: none) = _text-ref("interior-point-definition", "Interior point", "interior point", text: text, link-label: link-label)
#let exteriorpoint(text: none, link-label: none) = _text-ref("exterior-point-definition", "Exterior point", "exterior point", text: text, link-label: link-label)
#let accumulationpoint(text: none, link-label: none) = _text-ref("accumulation-point-definition", "Accumulationpoint point", "accumulation point", text: text, link-label: link-label)
#let topologycontinuous(text: none, link-label: none) = _text-ref("topology-continuity-definition", "Continuous (topology)", "continuous", text: text, link-label: link-label)
#let homeomorphism(text: none, link-label: none) = _text-ref("homeomorphism-definition", "Homeomorphism", "homeomorphism", text: text, link-label: link-label)
#let coordinatechange(text: none, link-label: none) = _text-ref("coordinate-change-definition", "Coordinate change", "coordinate change", text: text, link-label: link-label)
#let ifandonlyif(text: none, link-label: none) = _text-ref("logic-biconditional-logical-connective-definition", "Biconditional logical connective", "if and only if", text: text, link-label: link-label)
#let eulertheorem(text: none, link-label: none) = _text-ref("euler-theorem", "Euler's theorem", "Euler's theorem", text: text, link-label: link-label)
#let primen(text: none, link-label: none) = _text-ref("prime-number-definition", "Prime number", "prime", text: text, link-label: link-label)
#let coprime(text: none, link-label: none) = _text-ref("coprime-numbers-definition", "Coprime numbers", "coprime", text: text, link-label: link-label)
#let eulerformula(text: none, link-label: none) = _text-ref("euler-formula", "Euler's formula", "Euler's formula", text: text, link-label: link-label)
#let completnessaxiom(text: none, link-label: none) = _text-ref("completness-axiom", "Completness axiom", "completness axiom", text: text, link-label: link-label)
#let vectorspace(text: none, link-label: none) = _text-ref("vector-space-definition", "Vector space", "vector space", text: text, link-label: link-label)
#let affinespace(text: none, link-label: none) = _text-ref("affine-space-definition", "Affine space", "affine space", text: text, link-label: link-label)
#let vector(text: none, link-label: none) = _text-ref("vector-space-definition", "Vector", "vector", text: text, link-label: link-label)
#let affinepoint(text: none, link-label: none) = _text-ref("affine-space-definition", "Point", "point", text: text, link-label: link-label)
#let vsscalar(text: none, link-label: none) = _text-ref("vector-space-definition", "Scalar", "scalar", text: text, link-label: link-label)
#let linearcombination(text: none, link-label: none) = _text-ref("linear-combination-definition", "Linear combination", "linear combination", text: text, link-label: link-label)
#let linearlyindependent(text: none, link-label: none) = _text-ref("linear-independence-definition", "Linear independence", "linearly independent", text: text, link-label: link-label)
#let affinelyindependent(text: none, link-label: none) = _text-ref("affine-independence-definition", "Affinely independence", "affinely independent", text: text, link-label: link-label)
#let affineframe(text: none, link-label: none) = _text-ref("affine-frame-definition", "Affine frame", "affine frame", text: text, link-label: link-label)
#let crossproduct(text: none, link-label: none) = _text-ref("cross-product-definition", "Cross product", "cross product", text: text, link-label: link-label)
#let affinemap(text: none, link-label: none) = _text-ref("affine-map-definition", "Affine map", "affine map", text: text, link-label: link-label)
#let associatedlinearmap(text: none, link-label: none) = _text-ref("affine-associated-linear-map-definition", "Associated linear map", "associated linear map", text: text, link-label: link-label)
#let translationmap(text: none, link-label: none) = _text-ref("affine-translation-definition", "Translation", "translation", text: text, link-label: link-label)
#let homothety(text: none, link-label: none) = _text-ref("affine-homothety-definition", "Homothety", "homothety", text: text, link-label: link-label)
#let affinegroup(text: none, link-label: none) = _text-ref("affine-group-definition", "Affine group", "affine group", text: text, link-label: link-label)
#let homogeneouscoordinates(text: none, link-label: none) = _text-ref("affine-homogeneous-coordinates-definition", "Homogeneous coordinates", "homogeneous coordinates", text: text, link-label: link-label)
#let euclideanaffinespace(text: none, link-label: none) = _text-ref("euclidean-affine-space-definition", "Euclidean affine space", "Euclidean affine space", text: text, link-label: link-label)
#let affinedistance(text: none, link-label: none) = _text-ref("affine-euclidean-distance-definition", "Affine Euclidean distance", "distance", text: text, link-label: link-label)
#let affineisometry(text: none, link-label: none) = _text-ref("affine-isometry-definition", "Affine isometry", "affine isometry", text: text, link-label: link-label)
#let linearspantext(text: none, link-label: none) = _text-ref("span-definition", "Linear span", "linear span", text: text, link-label: link-label)
#let lineardimtext(text: none, link-label: none) = _text-ref("vector-space-dimension-definition", "Vector space dimension", "dimension", text: text, link-label: link-label)
#let basis(text: none, link-label: none) = _text-ref("basis-definition", "Basis of vector space", "basis", text: text, link-label: link-label)
#let matrix(text: none, link-label: none) = _text-ref("matrix-definition", "Matrix", "matrix", text: text, link-label: link-label)
#let matrixpivot(text: none, link-label: none) = _text-ref("row-echelon-form-definition", "Pivot", "pivot", text: text, link-label: link-label)
#let eigenvalue(text: none, link-label: none) = _text-ref("eigenvalues-eigenvectors-definition", "Eigenvalue", "eigenvalue", text: text, link-label: link-label)
#let eigenvector(text: none, link-label: none) = _text-ref("eigenvalues-eigenvectors-definition", "Eigenvector", "eigenvector", text: text, link-label: link-label)
#let eigenspace(text: none, link-label: none) = _text-ref("eigenspace-definition", "Eigenspace", "eigenspace", text: text, link-label: link-label)
#let diagonalizable(text: none, link-label: none) = _text-ref("diagonalizable-endomorphism-definition", "Diagonalizable", "diagonalizable", text: text, link-label: link-label)
#let characteristicpolynomial(text: none, link-label: none) = _text-ref("characteristic-polynomial-definition", "Characteristic polynomial", "characteristic polynomial", text: text, link-label: link-label)
#let endomorphismtrace(text: none, link-label: none) = _text-ref("endomorphism-trace-definition", "Trace of an endomorphism", "trace", text: text, link-label: link-label)
#let algebraicmultiplicity(text: none, link-label: none) = _text-ref("matrix-algebraic-multiplicity-definition", "Algebraic multiplicity", "algebraic multiplicity", text: text, link-label: link-label)
#let geometricmultiplicity(text: none, link-label: none) = _text-ref("matrix-geometric-multiplicity-definition", "Geometric multiplicity", "geometric multiplicity", text: text, link-label: link-label)
#let bilinearmap(text: none, link-label: none) = _text-ref("bilinear-map-definition", "Bilinear map", "bilinear map", text: text, link-label: link-label)
#let innerproduct(text: none, link-label: none) = _text-ref("inner-product-definition", "Inner product", "inner product", text: text, link-label: link-label)
#let innerproductspace(text: none, link-label: none) = _text-ref("inner-product-space-definition", "Inner product space", "inner product space", text: text, link-label: link-label)
#let orthogonal(text: none, link-label: none) = _text-ref("orthogonal-vectors-definition", "Orthogonal vectors", "orthogonal", text: text, link-label: link-label)
#let orthogonalprojection(text: none, link-label: none) = _text-ref("orthogonal-projection-definition", "Orthogonal projection", "orthogonal projection", text: text, link-label: link-label)
#let cauchyschwarz(text: none, link-label: none) = _text-ref("cauchy-schwarz-inequality", "Cauchy-Schwarz inequality", "Cauchy-Schwarz inequality", text: text, link-label: link-label)
#let inducedmetric(text: none, link-label: none) = _text-ref("inner-product-induced-metric-definition", "Induced metric", "induced metric", text: text, link-label: link-label)
#let innerproductmatrix(text: none, link-label: none) = _text-ref("inner-product-associated-matrix-definition", "Inner product matrix", "associated matrix", text: text, link-label: link-label)
#let symmetricmatrix(text: none, link-label: none) = _text-ref("symmetric-skew-symmetric-matrix-definition", "Symmetric matrix", "symmetric matrix", text: text, link-label: link-label)
#let hermitianmatrix(text: none, link-label: none) = _text-ref("hermitian-matrix-definition", "Hermitian matrix", "Hermitian matrix", text: text, link-label: link-label)
#let positivedefinitematrix(text: none, link-label: none) = _text-ref("positive-definite-matrix-definition", "Positive definite matrix", "positive definite matrix", text: text, link-label: link-label)
#let congruentmatrices(text: none, link-label: none) = _text-ref("congruent-matrices-definition", "Congruent matrices", "congruent matrices", text: text, link-label: link-label)
#let quadraticform(text: none, link-label: none) = _text-ref("quadratic-form-definition", "Quadratic form", "quadratic form", text: text, link-label: link-label)
#let symmetricbilinearform(text: none, link-label: none) = _text-ref("symmetric-bilinear-form-definition", "Symmetric bilinear form", "symmetric bilinear form", text: text, link-label: link-label)
#let associatedbilinearform(text: none, link-label: none) = _text-ref("quadratic-form-definition", "Associated bilinear form", "associated bilinear form", text: text, link-label: link-label)
#let quadraticformsign(text: none, link-label: none) = _text-ref("quadratic-form-sign-definition", "Sign of a quadratic form", "sign", text: text, link-label: link-label)
#let positivedefiniteform(text: none, link-label: none) = _text-ref("quadratic-form-sign-definition", "Positive definite quadratic form", "positive definite", text: text, link-label: link-label)
#let positivesemidefiniteform(text: none, link-label: none) = _text-ref("quadratic-form-sign-definition", "Positive semidefinite quadratic form", "positive semidefinite", text: text, link-label: link-label)
#let negativedefiniteform(text: none, link-label: none) = _text-ref("quadratic-form-sign-definition", "Negative definite quadratic form", "negative definite", text: text, link-label: link-label)
#let negativesemidefiniteform(text: none, link-label: none) = _text-ref("quadratic-form-sign-definition", "Negative semidefinite quadratic form", "negative semidefinite", text: text, link-label: link-label)
#let indefiniteform(text: none, link-label: none) = _text-ref("quadratic-form-sign-definition", "Indefinite quadratic form", "indefinite", text: text, link-label: link-label)
#let quadraticformmatrix(text: none, link-label: none) = _text-ref("quadratic-form-associated-matrix-definition", "Matrix associated to a quadratic form", "associated matrix", text: text, link-label: link-label)
#let congruentquadraticforms(text: none, link-label: none) = _text-ref("congruent-quadratic-forms-definition", "Congruent quadratic forms", "congruent quadratic forms", text: text, link-label: link-label)
#let sylvesternormalform(text: none, link-label: none) = _text-ref("sylvester-normal-form", "Sylvester normal form", "Sylvester normal form", text: text, link-label: link-label)
#let sylvesterlaw(text: none, link-label: none) = _text-ref("sylvester-law-of-inertia", "Sylvester's law of inertia", "Sylvester's law of inertia", text: text, link-label: link-label)
#let inertiaindices(text: none, link-label: none) = _text-ref("inertia-indices-definition", "Indices of inertia", "indices of inertia", text: text, link-label: link-label)
#let signature(text: none, link-label: none) = _text-ref("inertia-indices-definition", "Signature", "signature", text: text, link-label: link-label)
#let orthonormal(text: none, link-label: none) = _text-ref("orthonormal-collection-definition", "Orthonormal collection", "orthonormal", text: text, link-label: link-label)
#let orthonormalbasis(text: none, link-label: none) = _text-ref("orthonormal-basis-definition", "Orthonormal basis", "orthonormal basis", text: text, link-label: link-label)
#let fouriercoefficient(text: none, link-label: none) = _text-ref("orthonormal-basis-fourier-coefficients-definition", "Fourier coefficient", "Fourier coefficient", text: text, link-label: link-label)
#let parsevalidentity(text: none, link-label: none) = _text-ref("parseval-identity", "Parseval identity", "Parseval identity", text: text, link-label: link-label)
#let gramschmidt(text: none, link-label: none) = _text-ref("gram-schmidt-theorem", "Gram-Schmidt process", "Gram-Schmidt process", text: text, link-label: link-label)
#let rieszrepresentation(text: none, link-label: none) = _text-ref("riesz-representation-theorem", "Riesz representation theorem", "Riesz representation theorem", text: text, link-label: link-label)
#let adjointmap(text: none, link-label: none) = _text-ref("adjoint-map-definition", "Adjoint map", "adjoint", text: text, link-label: link-label)
#let selfadjoint(text: none, link-label: none) = _text-ref("self-adjoint-endomorphism-definition", "Self-adjoint endomorphism", "self-adjoint", text: text, link-label: link-label)
#let normalendomorphism(text: none, link-label: none) = _text-ref("normal-endomorphism-definition", "Normal endomorphism", "normal", text: text, link-label: link-label)
#let normalmatrix(text: none, link-label: none) = _text-ref("normal-matrix-definition", "Normal matrix", "normal matrix", text: text, link-label: link-label)
#let orthogonalmatrix(text: none, link-label: none) = _text-ref("orthogonal-matrix-definition", "Orthogonal matrix", "orthogonal matrix", text: text, link-label: link-label)
#let unitarymatrix(text: none, link-label: none) = _text-ref("unitary-matrix-definition", "Unitary matrix", "unitary matrix", text: text, link-label: link-label)
#let linearisometry(text: none, link-label: none) = _text-ref("linear-isometry-definition", "Linear isometry", "linear isometry", text: text, link-label: link-label)
#let orthogonalgroup(text: none, link-label: none) = _text-ref("orthogonal-group-definition", "Orthogonal group", "orthogonal group", text: text, link-label: link-label)
#let specialorthogonalgroup(text: none, link-label: none) = _text-ref("special-orthogonal-group-definition", "Special orthogonal group", "special orthogonal group", text: text, link-label: link-label)
#let unitarygroup(text: none, link-label: none) = _text-ref("unitary-group-definition", "Unitary group", "unitary group", text: text, link-label: link-label)
#let specialunitarygroup(text: none, link-label: none) = _text-ref("special-unitary-group-definition", "Special unitary group", "special unitary group", text: text, link-label: link-label)
#let spectraltheorem(text: none, link-label: none) = _text-ref("abstract-spectral-theorem", "Spectral theorem", "spectral theorem", text: text, link-label: link-label)
#let norm(text: none, link-label: none) = _text-ref("norm-definition", "Norm", "norm", text: text, link-label: link-label)
#let mnorm(text: none, link-label: none) = _text-ref("matrix-norm-definition", "Matrix norm", "matrix norm", text: text, link-label: link-label)
#let submulmnorm(text: none, link-label: none) = _text-ref("sub-multiplicative-matrix-norm-definition", "Sub-multiplicative matrix norm", "sub-multiplicative", text: text, link-label: link-label)
#let determinant(text: none, link-label: none) = _text-ref("determinant-definition", "Determinant", "determinant", text: text, link-label: link-label)
#let matrixminor(text: none, link-label: none) = _text-ref("matrix-minor-definition", "Matrix minor", "minor", text: text, link-label: link-label)
#let squaresubmatrix(text: none, link-label: none) = _text-ref("square-submatrix-definition", "Square submatrix", "square submatrix", text: text, link-label: link-label)
#let cramersrule(text: none, link-label: none) = _text-ref("cramer-rule-theorem", "Cramer's rule", "Cramer's rule", text: text, link-label: link-label)
#let sigmaalgebra(text: none, link-label: none) = _text-ref("sigma-algebra-definition", "Sigma algebra", "σ-algebra", text: text, link-label: link-label)
#let measure(text: none, link-label: none) = _text-ref("measure-definition", "Measure", "measure", text: text, link-label: link-label)
#let measurablespace(text: none, link-label: none) = _text-ref("measurable-space-definition", "Measurable space", "measurable space", text: text, link-label: link-label)
#let measurespace(text: none, link-label: none) = _text-ref("measure-space-definition", "Measure space", "measure space", text: text, link-label: link-label)
#let measurablemap(text: none, link-label: none) = _text-ref("measurable-map-definition", "Measurable map", "measurable map", text: text, link-label: link-label)
#let borelsigmaalgebra(text: none, link-label: none) = _text-ref("borel-sigma-algebra-metric-space-definition", "Borel sigma algebra", "Borel σ-algebra", text: text, link-label: link-label)
#let lebesguemeasure(text: none, link-label: none) = _text-ref("lebesgue-measure-meaning", "Lebesgue measure", "Lebesgue measure", text: text, link-label: link-label)
#let probabilityspace(text: none, link-label: none) = _text-ref("probability-space-definition", "Probability space", "probability space", text: text, link-label: link-label)
#let samplespace(text: none, link-label: none) = _text-ref("probability-space-definition", "Sample space", "sample space", text: text, link-label: link-label)
#let eventspace(text: none, link-label: none) = _text-ref("probability-space-definition", "Event space", "event space", text: text, link-label: link-label)
#let probabilitymeasure(text: none, link-label: none) = _text-ref("probability-space-definition", "Probability measure", "probability measure", text: text, link-label: link-label)
#let outcome(text: none, link-label: none) = _text-ref("outcome-definition", "Outcome", "outcome", text: text, link-label: link-label)
#let event(text: none, link-label: none) = _text-ref("event-definition", "Event", "event", text: text, link-label: link-label)
#let conditionalprobability(text: none, link-label: none) = _text-ref("conditional-probability-definition", "Conditional probability", "conditional probability", text: text, link-label: link-label)
#let samplespacepartition(text: none, link-label: none) = _text-ref("sample-space-partition-definition", "Sample space partition", "sample space partition", text: text, link-label: link-label)
#let totalprobabilitylaw(text: none, link-label: none) = _text-ref("total-probability-law", "Law of total probability", "law of total probability", text: text, link-label: link-label)
#let bayestheorem(text: none, link-label: none) = _text-ref("bayes-theorem", "Bayes' theorem", "Bayes' theorem", text: text, link-label: link-label)
#let finiteprobabilityspace(text: none, link-label: none) = _text-ref("finite-probability-space-definition", "Finite probability space", "finite probability space", text: text, link-label: link-label)
#let classicalprobability(text: none, link-label: none) = _text-ref("classical-finite-probability-definition", "Classical finite probability", "classical probability", text: text, link-label: link-label)
#let finiteadditivity(text: none, link-label: none) = _text-ref("finite-additivity-probability", "Finite additivity", "finite additivity", text: text, link-label: link-label)
#let finitesubadditivity(text: none, link-label: none) = _text-ref("finite-subadditivity-probability", "Finite subadditivity", "finite subadditivity", text: text, link-label: link-label)
#let inclusionexclusionprinciple(text: none, link-label: none) = _text-ref("inclusion-exclusion-principle", "Inclusion-exclusion principle", "inclusion-exclusion principle", text: text, link-label: link-label)
#let independentevents(text: none, link-label: none) = _text-ref("independent-events-definition", "Independent events", "independent events", text: text, link-label: link-label)
#let eventindependence(text: none, link-label: none) = _text-ref("independent-events-definition", "Event independence", "event independence", text: text, link-label: link-label)
#let independentfamilyofevents(text: none, link-label: none) = _text-ref("independent-family-events-definition", "Independent family of events", "independent family of events", text: text, link-label: link-label)
#let finiteuniformprobability(text: none, link-label: none) = _text-ref("finite-uniform-probability-definition", "Uniform probability on a finite sample space", "uniform probability", text: text, link-label: link-label)
#let orderedwithreplacement(text: none, link-label: none) = _text-ref("ordered-samples-with-replacement-definition", "Ordered samples with replacement", "ordered samples with replacement", text: text, link-label: link-label)
#let orderedwithoutreplacement(text: none, link-label: none) = _text-ref("ordered-samples-without-replacement-definition", "Ordered samples without replacement", "ordered samples without replacement", text: text, link-label: link-label)
#let unorderedwithoutreplacement(text: none, link-label: none) = _text-ref("unordered-samples-without-replacement-definition", "Unordered samples without replacement", "unordered samples without replacement", text: text, link-label: link-label)
#let unorderedwithreplacement(text: none, link-label: none) = _text-ref("unordered-samples-with-replacement-definition", "Unordered samples with replacement", "unordered samples with replacement", text: text, link-label: link-label)
#let bernoulliproductmodel(text: none, link-label: none) = _text-ref("finite-bernoulli-product-model", "Finite Bernoulli product model", "Bernoulli product model", text: text, link-label: link-label)
#let maxwellboltzmannoccupancy(text: none, link-label: none) = _text-ref("maxwell-boltzmann-occupancy-model", "Distinguishable-particle occupancy model", "distinguishable-particle occupancy model", text: text, link-label: link-label)
#let boseeinsteinoccupancy(text: none, link-label: none) = _text-ref("bose-einstein-occupancy-model", "Indistinguishable-particle occupancy model", "indistinguishable-particle occupancy model", text: text, link-label: link-label)
#let countableprobabilityspace(text: none, link-label: none) = _text-ref("countable-probability-space-definition", "Countable probability space", "countable probability space", text: text, link-label: link-label)
#let continuityfrombelow(text: none, link-label: none) = _text-ref("probability-continuity-from-below", "Continuity from below", "continuity from below", text: text, link-label: link-label)
#let continuityfromabove(text: none, link-label: none) = _text-ref("probability-continuity-from-above", "Continuity from above", "continuity from above", text: text, link-label: link-label)
#let sigmasubadditivity(text: none, link-label: none) = _text-ref("sigma-subadditivity-probability", "Sigma-subadditivity", "sigma-subadditivity", text: text, link-label: link-label)
#let discretedensity(text: none, link-label: none) = _text-ref("discrete-density-definition", "Discrete density", "discrete density", text: text, link-label: link-label)
#let countabletotalprobabilitylaw(text: none, link-label: none) = _text-ref("countable-total-probability-law", "Countable law of total probability", "countable law of total probability", text: text, link-label: link-label)
#let discretedistribution(text: none, link-label: none) = _text-ref("discrete-probability-distribution-definition", "Discrete probability distribution", "discrete probability distribution", text: text, link-label: link-label)
#let discreteuniformdistribution(text: none, link-label: none) = _text-ref("discrete-uniform-distribution-definition", "Discrete uniform distribution", "discrete uniform distribution", text: text, link-label: link-label)
#let bernoullidistribution(text: none, link-label: none) = _text-ref("bernoulli-distribution-definition", "Bernoulli distribution", "Bernoulli distribution", text: text, link-label: link-label)
#let binomialdistribution(text: none, link-label: none) = _text-ref("binomial-distribution-definition", "Binomial distribution", "binomial distribution", text: text, link-label: link-label)
#let hypergeometricdistribution(text: none, link-label: none) = _text-ref("hypergeometric-distribution-definition", "Hypergeometric distribution", "hypergeometric distribution", text: text, link-label: link-label)
#let multinomialdistribution(text: none, link-label: none) = _text-ref("multinomial-distribution-definition", "Multinomial distribution", "multinomial distribution", text: text, link-label: link-label)
#let geometricdistribution(text: none, link-label: none) = _text-ref("geometric-distribution-definition", "Geometric distribution", "geometric distribution", text: text, link-label: link-label)
#let poissondistribution(text: none, link-label: none) = _text-ref("poisson-distribution-definition", "Poisson distribution", "Poisson distribution", text: text, link-label: link-label)
#let discreterandomvariable(text: none, link-label: none) = _text-ref("discrete-random-variable-definition", "Discrete random variable", "discrete random variable", text: text, link-label: link-label)
#let lawofrandomvariable(text: none, link-label: none) = _text-ref("law-of-random-variable-definition", "Law of a random variable", "law", text: text, link-label: link-label)
#let randomvariabledensity(text: none, link-label: none) = _text-ref("discrete-random-variable-density-definition", "Discrete density of a random variable", "discrete density", text: text, link-label: link-label)
#let randomvariablesupport(text: none, link-label: none) = _text-ref("discrete-random-variable-support-definition", "Support of a discrete random variable", "support", text: text, link-label: link-label)
#let discreterandomvector(text: none, link-label: none) = _text-ref("discrete-random-vector-definition", "Discrete random vector", "discrete random vector", text: text, link-label: link-label)
#let jointlaw(text: none, link-label: none) = _text-ref("joint-and-marginal-laws-random-vector-definition", "Joint law", "joint law", text: text, link-label: link-label)
#let jointdensity(text: none, link-label: none) = _text-ref("joint-law-density-definition", "Joint density", "joint density", text: text, link-label: link-label)
#let marginallaw(text: none, link-label: none) = _text-ref("joint-and-marginal-laws-random-vector-definition", "Marginal law", "marginal law", text: text, link-label: link-label)
#let marginaldensity(text: none, link-label: none) = _text-ref("marginal-law-density-definition", "Marginal density", "marginal density", text: text, link-label: link-label)
#let independentdiscreterandomvariables(text: none, link-label: none) = _text-ref("independent-discrete-random-variables-definition", "Independent discrete random variables", "independent discrete random variables", text: text, link-label: link-label)
#let iiddiscreterandomvariables(text: none, link-label: none) = _text-ref("iid-discrete-random-variables-definition", "Independent and identically distributed discrete random variables", "independent and identically distributed discrete random variables", text: text, link-label: link-label)
#let densityfactorizationcriterion(text: none, link-label: none) = _text-ref("independent-discrete-random-variables-density-factorization", "Density factorization criterion", "density factorization criterion", text: text, link-label: link-label)
#let convolutionformula(text: none, link-label: none) = _text-ref("discrete-sum-independent-convolution-formula", "Convolution formula", "convolution formula", text: text, link-label: link-label)
#let discreteconvolution(text: none, link-label: none) = _text-ref("discrete-convolution-interpretation", "Discrete convolution", "discrete convolution", text: text, link-label: link-label)
#let expectedvalue(text: none, link-label: none) = _text-ref("expected-value-random-variable-definition", "Expected value", "expected value", text: text, link-label: link-label)
#let finiteexpectedvalue(text: none, link-label: none) = _text-ref("finite-expected-value-definition", "Finite expected value", "finite expected value", text: text, link-label: link-label)
#let finitemoment(text: none, link-label: none) = _text-ref("finite-moment-random-variable-definition", "Finite moment", "finite moment", text: text, link-label: link-label)
#let mixedmoment(text: none, link-label: none) = _text-ref("mixed-moment-discrete-random-variables-definition", "Mixed moment", "mixed moment", text: text, link-label: link-label)
#let jenseninequality(text: none, link-label: none) = _text-ref("discrete-jensen-inequality", "Jensen's inequality", "Jensen's inequality", text: text, link-label: link-label)
#let probabilitycauchyschwarz(text: none, link-label: none) = _text-ref("probability-cauchy-schwarz-inequality", "Cauchy-Schwarz inequality", "Cauchy-Schwarz inequality", text: text, link-label: link-label)
#let randomvariable(text: none, link-label: none) = _text-ref("random-variable-definition", "Random variable", "random variable", text: text, link-label: link-label)
#let randomvector(text: none, link-label: none) = _text-ref("random-vector-definition", "Random vector", "random vector", text: text, link-label: link-label)
#let independentrandomvariables(text: none, link-label: none) = _text-ref("independent-random-variables-definition", "Independent random variables", "independent random variables", text: text, link-label: link-label)
#let absolutelycontinuousrandomvariable(text: none, link-label: none) = _text-ref("absolutely-continuous-random-variable-definition", "Absolutely continuous random variable", "absolutely continuous random variable", text: text, link-label: link-label)
#let absolutelycontinuousrandomvector(text: none, link-label: none) = _text-ref("absolutely-continuous-random-vector-definition", "Absolutely continuous random vector", "absolutely continuous random vector", text: text, link-label: link-label)
#let continuousjointdensity(text: none, link-label: none) = _text-ref("absolutely-continuous-random-vector-definition", "Joint density", "joint density", text: text, link-label: link-label)
#let continuousmarginaldensity(text: none, link-label: none) = _text-ref("marginal-density-continuous-random-vector", "Marginal density", "marginal density", text: text, link-label: link-label)
#let affinedensitytransformation(text: none, link-label: none) = _text-ref("affine-transformation-density", "Density under an invertible affine transformation", "affine density transformation", text: text, link-label: link-label)
#let distributionfunction(text: none, link-label: none) = _text-ref("distribution-function-definition", "Distribution function", "distribution function", text: text, link-label: link-label)
#let cdf(text: none, link-label: none) = _text-ref("distribution-function-definition", "Distribution function", "CDF", text: text, link-label: link-label)
#let probabilityatom(text: none, link-label: none) = _text-ref("probability-atom-definition", "Atom of a probability measure", "atom", text: text, link-label: link-label)
#let absolutelycontinuousmeasure(text: none, link-label: none) = _text-ref("absolute-continuity-lebesgue-definition", "Absolutely continuous measure", "absolutely continuous measure", text: text, link-label: link-label)
#let probabilitydensity(text: none, link-label: none) = _text-ref("probability-density-definition", "Density of an absolutely continuous probability measure", "density", text: text, link-label: link-label)
#let diracmeasure(text: none, link-label: none) = _text-ref("dirac-measure-definition", "Dirac measure", "Dirac measure", text: text, link-label: link-label)
#let lebesguedecomposition(text: none, link-label: none) = _text-ref("lebesgue-decomposition-probability-measure", "Lebesgue decomposition", "Lebesgue decomposition", text: text, link-label: link-label)
#let continuousuniformdistribution(text: none, link-label: none) = _text-ref("continuous-uniform-distribution-definition", "Uniform distribution on an interval", "uniform distribution", text: text, link-label: link-label)
#let exponentialdistribution(text: none, link-label: none) = _text-ref("exponential-distribution-definition", "Exponential distribution", "exponential distribution", text: text, link-label: link-label)
#let gaussiandistribution(text: none, link-label: none) = _text-ref("gaussian-distribution-definition", "Gaussian distribution", "Gaussian distribution", text: text, link-label: link-label)
#let standardgaussianmoments(text: none, link-label: none) = _text-ref("standard-gaussian-moments", "Moments of the standard Gaussian distribution", "moments of the standard Gaussian distribution", text: text, link-label: link-label)
#let expectedvector(text: none, link-label: none) = _text-ref("expected-vector-definition", "Expected vector", "expected vector", text: text, link-label: link-label)
#let covariancematrix(text: none, link-label: none) = _text-ref("covariance-matrix-definition", "Covariance matrix", "covariance matrix", text: text, link-label: link-label)
#let standardgaussianvector(text: none, link-label: none) = _text-ref("standard-gaussian-vector-definition", "Standard Gaussian vector", "standard Gaussian vector", text: text, link-label: link-label)
#let gaussianvector(text: none, link-label: none) = _text-ref("gaussian-vector-definition", "Gaussian vector", "Gaussian vector", text: text, link-label: link-label)
#let conditionallaw(text: none, link-label: none) = _text-ref("conditional-law-discrete-definition", "Conditional law", "conditional law", text: text, link-label: link-label)
#let conditionaldiscretedensity(text: none, link-label: none) = _text-ref("conditional-discrete-density-definition", "Conditional discrete density", "conditional discrete density", text: text, link-label: link-label)
#let conditionaldensity(text: none, link-label: none) = _text-ref("conditional-density-absolutely-continuous-definition", "Conditional density", "conditional density", text: text, link-label: link-label)
#let conditionalexpectation(text: none, link-label: none) = _text-ref("discrete-conditional-expectation-definition", "Conditional expected value", "conditional expected value", text: text, link-label: link-label)
#let convergenceindistribution(text: none, link-label: none) = _text-ref("convergence-in-distribution-definition", "Convergence in distribution", "convergence in distribution", text: text, link-label: link-label)
#let convergenceinprobability(text: none, link-label: none) = _text-ref("convergence-in-probability-definition", "Convergence in probability", "convergence in probability", text: text, link-label: link-label)
#let almostsureconvergence(text: none, link-label: none) = _text-ref("almost-sure-convergence-definition", "Almost sure convergence", "almost sure convergence", text: text, link-label: link-label)
#let borelcantellilemma(text: none, link-label: none) = _text-ref("borel-cantelli-lemma", "Borel-Cantelli lemma", "Borel-Cantelli lemma", text: text, link-label: link-label)
#let iidrandomvariables(text: none, link-label: none) = _text-ref("iid-random-variables-definition", "Independent and identically distributed random variables", "independent and identically distributed random variables", text: text, link-label: link-label)
#let samplemean(text: none, link-label: none) = _text-ref("sample-mean-definition", "Sample mean", "sample mean", text: text, link-label: link-label)
#let markovinequality(text: none, link-label: none) = _text-ref("markov-inequality", "Markov inequality", "Markov inequality", text: text, link-label: link-label)
#let chebyshevinequality(text: none, link-label: none) = _text-ref("chebyshev-inequality", "Chebyshev inequality", "Chebyshev inequality", text: text, link-label: link-label)
#let weaklawlargenumbers(text: none, link-label: none) = _text-ref("weak-law-large-numbers", "Weak law of large numbers", "weak law of large numbers", text: text, link-label: link-label)
#let stronglawlargenumbers(text: none, link-label: none) = _text-ref("strong-law-large-numbers", "Strong law of large numbers", "strong law of large numbers", text: text, link-label: link-label)
#let centrallimittheorem(text: none, link-label: none) = _text-ref("central-limit-theorem", "Central limit theorem", "central limit theorem", text: text, link-label: link-label)
#let graph(text: none, link-label: none) = _text-ref("graph-definition", "Graph", "graph", text: text, link-label: link-label)
#let walk(text: none, link-label: none) = _text-ref("walk-definition", "Walk", "walk", text: text, link-label: link-label)
#let path(text: none, link-label: none) = _text-ref("path-definition", "Path", "path", text: text, link-label: link-label)
#let polynomial(text: none, link-label: none) = _text-ref("polynomial-definition", "Polynomial", "polynomial", text: text, link-label: link-label)
#let multiplicity(text: none, link-label: none) = _text-ref("polynomial-root-multiplicity-definition", "Root multiplicity", "multiplicity", text: text, link-label: link-label)
#let algebraicequation(text: none, link-label: none) = _text-ref("algebraic-equation-definition", "Algebraic equation", "algebraic equation", text: text, link-label: link-label)
#let sequence(text: none, link-label: none) = _text-ref("sequence-definition", "Sequence", "sequence", text: text, link-label: link-label)
#let subsequence(text: none, link-label: none) = _text-ref("subsequence-definition", "Subsequence", "subsequence", text: text, link-label: link-label)
#let realcontinuous(text: none, link-label: none) = _text-ref("real-continuity-definition", "Continuity", "continuous", text: text, link-label: link-label)
#let differentiable(text: none, link-label: none) = _text-ref("real-function-derivative-definition", "Differentiable", "differentiable", text: text, link-label: link-label)
#let rationalfunc(text: none, link-label: none) = _text-ref("rational-function-definition", "Rational function", "rational", text: text, link-label: link-label)
#let primitivefunc(text: none, link-label: none) = _text-ref("primitive-function-definition", "Primitive function", "primitive", text: text, link-label: link-label)
#let series(text: none, link-label: none) = _text-ref("series-definition", "Series", "series", text: text, link-label: link-label)
#let partialsum(text: none, link-label: none) = _text-ref("series-definition", "Partial sum", "partial sum", text: text, link-label: link-label)
#let seriesconverges(text: none, link-label: none) = _text-ref("series-definition", "Series convergence", "converges", text: text, link-label: link-label)
#let seriesdiverges(text: none, link-label: none) = _text-ref("series-definition", "Series divergence", "diverges", text: text, link-label: link-label)
#let seriesoscillates(text: none, link-label: none) = _text-ref("series-definition", "Series oscillates", "oscillates", text: text, link-label: link-label)
#let convergesabsolutely(text: none, link-label: none) = _text-ref("absolute-convergence-definition", "Absolute convergence", "converges absolutely", text: text, link-label: link-label)
#let geometricseries(text: none, link-label: none) = _text-ref("geometric-series-definition", "Geometric series", "geometric series", text: text, link-label: link-label)
#let telescopicseries(text: none, link-label: none) = _text-ref("telescopic-series-definition", "Telescopic series", "telescopic series", text: text, link-label: link-label)
#let harmonicseries(text: none, link-label: none) = _text-ref("harmonic-series-definition", "Harmonic series", "harmonic series", text: text, link-label: link-label)
#let lhopitalrule(text: none, link-label: none) = _text-ref("hopital-rule", "L'Hospital's rule", "L'Hôpital Rule", text: text, link-label: link-label)
#let squeezetheorem(text: none, link-label: none) = _text-ref("squeeze-theorem", "Squeeze theorem", "squeeze theorem", text: text, link-label: link-label)
#let logarithm(text: none, link-label: none) = _text-ref("logarithm-definition", "Logarithm", "logarithm", text: text, link-label: link-label)


// Friendly aliases for the two most common collision-prone text commands.
#let setref = set-term
#let function-term = function

// ---------- Trigonometric operators ----------
#let sin = _math-ref("sine-definition", "Sine function", $"sin"$, operator: true)
#let cos = _math-ref("cosine-definition", "Cosine function", $"cos"$, operator: true)
#let tan = _math-ref("tangent-definition", "Tangent function", $"tan"$, operator: true)
#let sinh = _math-ref("hyperbolic-sine-definition", "Hyperbolic sine function", $"sinh"$, operator: true)
#let cosh = _math-ref("hyperbolic-cosine-definition", "Hyperbolic cosine function", $"cosh"$, operator: true)
#let tanh = _math-ref("hyperbolic-tangent-definition", "Hyperbolic tangent function", $"tanh"$, operator: true)

// ---------- Set theory and functions ----------
#let image-op = _math-ref("function-image-definition", "Function image", $"im"$, operator: true)
#let inclusionmap = _math-ref("inclusion-map-definition", "Inclusion map", $ι$, operator: true)
#let identityfunc = _math-ref("identity-function-definition", "Identity function", $"Id"$)
#let indicator = _math-ref("indicator-function-definition", "Indicator function", $χ$)
#let setofstepfunctions = _math-ref("step-function-definition", "Set of all step functions", $cal(S)$)
#let setoflineartransformations = _math-ref("linear-transformation-definition", "Set of all linear transformations", $cal(L)$)
#let ltkernel = _math-ref("linear-transformation-kernel-definition", "Kernel of a linear transformation", $"ker"$, operator: true)
#let ltimage = _math-ref("linear-transformation-image-definition", "Image of a linear transformation", $"Im"$, operator: true)

// Unicode U+2A1B/U+2A1C are the integral-with-overbar and integral-with-underbar glyphs.
#let lrint = $⨜$
#let urint = $⨛$
#let lriint = $⨜⨜$
#let uriint = $⨛⨛$

#let subgroup-leq = _math-ref("subgroup-definition", "Subgroup", $<=$, class: "relation")
#let subring-leq = _math-ref("subring-definition", "Subring", $<=$, class: "relation")
#let submonoid-subseteq = _math-ref("submonoid-definition", "Submonoid", $⊆$, class: "relation")
#let groupcenter = _math-ref("center-of-group-definition", "Center of a group", $"Z"$)
#let groupcentralizer = _math-ref("centralizer-group-definition", "Centralizer", $"C"$)
#let groupnormalizer = _math-ref("normalizer-group-definition", "Normalizer", $N$)
#let gengrp(body) = [#_math-ref("generating-set-of-group-definition", "Generating set of a group", $⟨$, class: "opening")#body#_math-ref("generating-set-of-group-definition", "Generating set of a group", $⟩$, class: "closing")]
#let dihedralgrp = _math-ref("dihedral-group-definition", "Dihedral group", $D$)
#let symgrp = _math-ref("symmetric-group-definition", "Symmetric group", $"Sym"$)
#let permgrp = _math-ref("permutation-group-definition", "Permutation group", $"Sym"$)
#let supp = _math-ref("permutation-support-definition", "Support of a permutation", $"Supp"$, operator: true)
#let kcycle(..items) = [#_math-ref("k-cycle-definition", "K-cycle", $($, class: "opening")#items.pos().join(h(0.35em))#_math-ref("k-cycle-definition", "K-cycle", $)$, class: "closing")]
#let normalsubgrp = _math-ref("normal-subgroup-definition", "Normal subgroup", $⊴$, class: "relation")
#let idealin = _math-ref("ring-ideal-definition", "Ring ideal", $⊴$, class: "relation")
#let stabilizer = _math-ref("stabilizer-definition", "Stabilizer", $"Stab"$, operator: true)
#let lextsemidirectprod = _math-ref("group-external-semidirect-product-definition", "External semidirect product", $⋉$, class: "binary")
#let rextsemidirectprod = _math-ref("group-external-semidirect-product-definition", "External semidirect product", $⋊$, class: "binary")
#let lintsemidirectprod = _math-ref("group-internal-semidirect-product-definition", "Internal semidirect product", $⋉$, class: "binary")
#let rintsemidirectprod = _math-ref("group-internal-semidirect-product-definition", "Internal semidirect product", $⋊$, class: "binary")
#let fieldtwo = _math-ref("binary-field-f2-definition", "The field F2", $𝔽_2$)
#let quotientfield = _math-ref("field-of-fractions-definition", "Field of fractions", $"Quot"$, operator: true)
#let identity = _math-ref("identity-function-definition", "Identity function", $"Id"$, class: "binary")
#let inversefunction = _math-ref("inverse-function-definition", "Inverse function", $-1$)

#let subseteq = _math-ref("subset-definition", "Subset", $⊆$, class: "relation")
#let notsubseteq = _math-ref("subset-definition", "Not subset", $⊈$, class: "relation")
#let subset = _math-ref("proper-subset-definition", "Proper subset", $⊂$, class: "relation")
#let notsubset = _math-ref("proper-subset-definition", "Not proper subset", $⊄$, class: "relation")
#let supseteq = _math-ref("subset-definition", "Subset", $⊇$, class: "relation")
#let notsupseteq = _math-ref("subset-definition", "Not subset", $⊉$, class: "relation")
#let supset = _math-ref("proper-subset-definition", "Proper subset", $⊃$, class: "relation")
#let notsupset = _math-ref("proper-subset-definition", "Not proper subset", $⊅$, class: "relation")
#let powerset = _math-ref("power-set-definition", "Power set", $cal(P)$)
#let cardinality(body) = [#_math-ref("cardinality-definition", "Cardinality", $|$, class: "fence")#body#_math-ref("cardinality-definition", "Cardinality symbol", $|$, class: "fence")]
#let elementperiod(body) = [#_math-ref("group-element-period-definition", "Element period", $|$, class: "fence")#body#_math-ref("group-element-period-definition", "Element period", $|$, class: "fence")]
#let setequivalent = _math-ref("set-equivalence-definition", "Set equivalence", $∼$, class: "relation")
#let curvelength = _math-ref("curve-length-definition", "Length of a curve", $L$)
#let curveequivalent = _math-ref("curve-equivalence-definition", "Curve equivalence", $∼$, class: "relation")
#let union = _math-ref("union-definition", "Set union", $∪$, class: "binary")
#let intersection = _math-ref("intersection-definition", "Set intersection", $∩$, class: "binary")
#let difference = _math-ref("difference-definition", "Set difference", $∖$, class: "binary")
#let cartesianprod = _math-ref("cartesian-product-definition", "Cartesian product", $×$, class: "binary")
#let disjointunion = _math-ref("disjoint-union-definition", "Disjoint union", $⊔$, class: "binary")

// Exact LaTeX-name aliases for identifiers written with compact spelling.
#let subgroupleq = subgroup-leq
#let subringleq = subring-leq
#let submonoidsubseteq = submonoid-subseteq

// ---------- Category theory ----------
#let catob = _math-ref("category-definition", "Objects of a category", $"Ob"$, operator: true)
#let cathom = _math-ref("category-definition", "Morphisms of a category", $"Hom"$, operator: true)
#let dualcat = _math-ref("dual-category-definition", "Dual category", $"op"$)
#let catvect = _math-ref("vector-category-definition", "Vector category", $bold("Vect")$)
#let catset = _math-ref("set-category-definition", "Set category", $bold("Set")$)
#let cattop = _math-ref("top-category-definition", "Topology category", $bold("Top")$)
#let catopen = _math-ref("open-sets-category-definition", "Category of open sets", $"Open"$)
#let subojects = _math-ref("suboject-definition", "Subobjects", $"Sub"$)
#let slicecat = _math-ref("slice-category-definition", "Slice category", $"/"$, class: "binary")

// ---------- Metric spaces and topology ----------
#let distancefunction(body: none) = _append(_math-ref("distance-function-definition", "Distance function", if body == none { $d$ } else { body }), none)
#let msdiameter = _math-ref("metric-space-diameter-definition", "Diameter", $"diam"$, operator: true)
#let ball = _math-ref("metricspaces-open-ball-definition", "Open ball", $B$)
#let boundary(space: none, body: none) = _subscripted(
  _math-ref("boundary-definition", "Boundary", $∂$),
  subscript: space,
  tail: body,
)
#let interior(space: none, body: none) = _subscripted(
  _math-ref("interior-set-definition", "Interior set", $"int"$, operator: true),
  subscript: space,
  tail: body,
)
#let closure(space: none, body: none) = _subscripted(
  _math-ref("closure-definition", "Closure", $"cl"$, operator: true),
  subscript: space,
  tail: body,
)
#let metrictopology = _math-ref("metric-topology-definition", "Metric topology", $cal(T)$)
#let topologyconverges = _math-ref("topology-convergence-definition", "Converges (topology)", $→$, class: "relation")
#let simplex = _math-ref("n-simplex-definition", "Simplex", $Δ$)

// ---------- Linear algebra and analysis ----------
#let gradient = _math-ref("gradient-definition", "Gradient", $∇$)
#let jacobian = _math-ref("jabocian-matrix-definition", "Jabocian", $J$)
#let hessian = _math-ref("hessian-matrix-definition", "Hessian", $H$)
#let groupisomorphic = _math-ref("group-isomorphism-definition", "Group isomorphism", $≅$, class: "relation")
#let ringisomorphic = _math-ref("ring-isomorphism-definition", "Ring isomorphism", $≅$, class: "relation")
#let grpker = _math-ref("group-kernel-definition", "Kernel of a group", $"ker"$, operator: true)
#let ringker = _math-ref("ring-kernel-definition", "Kernel of a ring", $"ker"$, operator: true)
#let linearspan = _math-ref("span-definition", "Linear span", $"span"$, operator: true)
#let lineardim = _math-ref("vector-space-dimension-definition", "Vector space dimension", $"dim"$, operator: true)
#let affgrp = _math-ref("affine-group-definition", "Affine group", $"GAff"$, operator: true)
#let matrices = _math-ref("matrix-definition", "Set of matrices", $"Mat"$)
#let columnspace = _math-ref("column-space-definition", "Column space", $cal(C)$, operator: true)
#let rowspace = _math-ref("row-space-definition", "Row space", $cal(R)$, operator: true)
#let mrank = _math-ref("matrix-rank-definition", "Rank of a matrix", $"rank"$, operator: true)
#let ltrank = _math-ref("linear-transformation-rank-definition", "Rank of a linear transformation", $"rank"$, operator: true)
#let transpose = _math-ref("matrix-transpose-definition", "Transpose operator", $t$)
#let spectralradius = _math-ref("spectral-radius-definition", "Spectral radius", $ρ$)
#let conjtrans = _math-ref("matrix-conjugate-transpose-definition", "Conjugate transpose operator", $†$)
#let det = _math-ref("determinant-definition", "Matrix determinant", $"det"$, operator: true)
#let cofactor = _math-ref("cofactor-matrix-definition", "Cofactor matrix", $C$)
#let trace = _math-ref("matrix-trace-definition", "Trace of a matrix", $"tr"$, operator: true)
#let identmatrix(n) = _math-ref("identity-matrix-definition", "Identity matrix", $I_#n$)

// ---------- Logic and arithmetic ----------
#let iff = _math-ref("logic-biconditional-logical-connective-definition", "Biconditional logical connective", $⇔$, class: "binary")
#let implies = _math-ref("logic-sufficiency-definition", "Sufficiency logical connective", $⇒$, class: "binary")
#let impliedby = _math-ref("logic-necessity-definition", "Necessity logical connective", $⇐$, class: "binary")
#let lnot = _math-ref("logic-logical-negation-definition", "Logical negation", $¬$, class: "unary")
#let land = _math-ref("logic-logical-conjunction-definition", "Logical conjunction", $∧$, class: "binary")
#let lor = _math-ref("logic-logical-disjunction-definition", "Logical disjunction", $∨$, class: "binary")
#let lxor = _label-math("Exclusive disjunction", $⊻$, operator: true)
#let divides = _math-ref("divide-operator-definition", "Divide operator", $∣$, class: "relation")
#let factorial = _math-ref("factorial-definition", "Factorial", $!$, class: "closing")
#let eulertotient = _math-ref("euler-totient-function-definition", "Euler's totient function", $φ$)
#let gcd = _math-ref("greatest-common-divisor-definition", "Greatest common divisor", $"gcd"$, operator: true)
#let lcm = _math-ref("least-common-multiple-definition", "Least common multiple", $"lcm"$, operator: true)

// ---------- Complex analysis and number systems ----------
#let Re = _math-ref("complex-real-part-definition", "Real part function", $ℜ$, operator: true)
#let Im = _math-ref("complex-imaginary-part-definition", "Imaginary part function", $ℑ$, operator: true)
#let gammafunc = _math-ref("gamma-function-definition", "Gamma function", $Γ$)
#let complexconj = _math-ref("complex-conjugate-definition", "Complex conjugate", $∗$)
#let naturalnumbers = _math-ref("natural-numbers-definition", "Natural numbers", $ℕ$)
#let integers = _math-ref("integers-definition", "Integer numbers", $ℤ$)
#let realnumbers = _math-ref("real-numbers-definition", "Real numbers", $ℝ$)
#let extendedrealnumbers = _math-ref("extended-real-line-definition", "Extended real numbers", $overline(RR)$)
#let rationalnumbers = _math-ref("rational-numbers-definition", "Rational numbers", $ℚ$)
#let complexnumbers = _math-ref("complex-numbers-definition", "Complex numbers", $ℂ$)
#let zetafn = _math-ref("zeta-function-definition", "Zeta function", $ζ$)
#let primecounting = _math-ref("prime-counting-function-definition", "Prime counting function", $π$)
#let mobiusfn = _math-ref("mobius-function-definition", "Mobius function", $μ$)

// ---------- Probability ----------
#let eqdist = _math-ref("equality-in-law-definition", "Equality in law", $=_d$, class: "relation")
#let asequal = _math-ref("almost-sure-equality-definition", "Almost sure equality", $=_("a.s.")$, class: "relation")
#let expectation = _math-ref("expected-value-random-variable-definition", "Expected value", $𝔼$, operator: true)
#let variance = _math-ref("variance-covariance-definition", "Variance", $"Var"$, operator: true)
#let covariance = _math-ref("variance-covariance-definition", "Covariance", $"Cov"$, operator: true)
#let correlationcoefficient = _math-ref("correlation-coefficient-definition", "Correlation coefficient", $Γ$)

// ---------- Miscellaneous and calculus ----------
#let graphdeg = _math-ref("graph-vertex-degree-definition", "Graph vertex degree", $"deg"$, operator: true)
#let kronecker = _math-ref("kronecker-delta-definition", "Kronecker delta", $δ$)
#let laplacetf = _math-ref("laplace-transform-definition", "Laplace transform", $cal(L)$)
#let invlaplacetf = _math-ref("inverse-laplace-transform-definition", "Inverse Laplace transform", $cal(L)^(-1)$)
#let polynomialdeg = _math-ref("polynomial-degree-definition", "Polynomial degree", $"deg"$, operator: true)
#let seqconverges = _math-ref("sequence-limit-definition", "Converges", $→$, class: "relation")
#let derivativeD = _math-ref("real-function-derivative-definition", "Derivative", $D$)
#let continuityclass = _math-ref("continuity-class-definition", "Continuity class", $cal(C)$)
#let asymptotic = _math-ref("asymptotic-equivalence-definition", "Asymptotic equivalence", $∼$, class: "relation")
#let bigO = _math-ref("big-o-definition", "Big-O notation", $cal(O)$)
#let littleO = _math-ref("little-o-definition", "Little-O notation", $o$)
#let bigomega = _math-ref("big-omega-definition", "Big-Omega notation", $Ω$)
#let littleomega = _math-ref("little-omega-definition", "Little-Omega notation", $ω$)
#let bigtheta = _math-ref("big-theta-definition", "Big-Theta notation", $Θ$)
#let log = _math-ref("logarithm-definition", "Logarithm", $"log"$, operator: true)
#let ln = _math-ref("natural-logarithm-definition", "Natural logarithm", $"log"$, operator: true)
#let sup = _math-ref("supremum-definition", "Supremum", $"sup"$, operator: true)
#let inf = _math-ref("infimum-definition", "Infimum", $"inf"$, operator: true)
#let limsup = _math-ref("limit-superior-definition", "Limit superior", $"lim sup"$, operator: true)
#let liminf = _math-ref("limit-inferior-definition", "Limit inferior", $"lim inf"$, operator: true)
#let eulernumber = _math-ref("euler-number-definition", "Euler number", $e$)
#let picircle = _math-ref("circle-constant-definition", "Circle constant", $π$)

// ---------- Label-only mathematical symbols ----------
#let suchthat = _label-math("Such that", $|$, class: "relation")
#let forall = _label-math("For all", $∀$, class: "unary")
#let exists = _label-math("There exists", $∃$, class: "unary")
#let nexists = _label-math("There does not exists", $∄$, class: "unary")
#let insym = _label-math("Set membership", $∈$, class: "relation")
#let in-sym = insym
#let ni = _label-math("Set membership", $∋$, class: "relation")
#let emptyset = _label-math("Empty set", $∅$, operator: true)
#let lightning = _label-math("Contradiction!", $↯$)
#let triangleq = _label-math("Is defined as", $≝$, class: "relation")
#let equiv = _label-math("Is equivalent to", $≡$, class: "relation")
#let propto = _label-math("Is proportional to", $∝$, class: "relation")
#let mapsto = _label-math("Maps to", $↦$, class: "relation")
#let exceptzero = _label-math("Except zero", $∗$)
#let fromto = _label-math("From ... to ...", $→$, class: "relation")
#let inclusion = _label-math("Inclusion from ... to ...", $↪$, class: "relation")
#let tendsto = _label-math("Tends to", $→$, class: "relation")
#let triangleineqleq = _label-math("Triangle inequality", $⊴$, class: "relation")

#let warningsign = text(fill: red, weight: "bold")[⚠]
#let todo = [Work in progress #warningsign this section still has to be completed!]
