#!/bin/bash

if [ $# -gt 0 ]; then
    files=$(find latex/ snippets/ courses/ universes/ pages/ -type f -name "*$1*")

    for file in $files; do
        ./compile "$file"
    done
else
    echo "Provide an argument"
fi