#!/bin/bash

# Compiles current changes in `git status`

modified_files=$(git status --porcelain | grep -E '^( M| M|A|M|\?\?)' | awk '{print $2}')

for file in $modified_files; do
    # Check if the file starts with "source/"
    if [[ $file == source/* ]]; then
        new_file=${file#source/}
        ./compile "$new_file"
    fi
done