#!/bin/bash

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

# Run git pull
output=$(git --git-dir="$SCRIPT_DIR/../.git" --work-tree="$SCRIPT_DIR/.." pull)

# Check if output contains "Already up to date."
if [[ "$output" != *"Already up to date."* ]]; then
    ./compile --last-pull
fi