#!/bin/bash

# Run git pull
output=$(git pull)

# Check if output contains "Already up to date."
if [[ "$output" != *"Already up to date."* ]]; then
    ./compile --last-pull
else
    echo "Already up to date"
fi