#!/bin/bash

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
cd $SCRIPT_DIR

# Run git pull
output=$(git pull)

# Check if output contains "Already up to date."
if [[ "$output" != *"Already up to date."* ]]; then
    ./compile --last-pull
fi